/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "JMOutlineViewController.h"

@interface ABOutlineViewController : JMOutlineViewController
{
    BOOL _styleChanged;
}

- (void)setStyleChanged:(BOOL)fp8;
- (BOOL)styleChanged;
- (void)reportScreenAppearanceToAnalytics;
- (id)customScreenNameForAnalytics;
- (id)navigationBar;
- (void)respondToStyleChange;
- (void)respondToStyleChangeNotification;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)loadView;
- (id)init;
- (void)dealloc;

@end

