/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@class JMOutlineTableView, JMRefreshHeaderView, NSMutableArray, UIImageView, UIView;

@protocol JMRefreshHeaderDelegate <NSObject>

@end

@protocol JMOutlineNodeProtocol <NSObject>

@end

@interface JMOutlineViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, JMRefreshHeaderDelegate, JMOutlineNodeProtocol>
{
    BOOL showFloatingHeader_;
    BOOL _isReloadingNodes;
    NSMutableArray *nodes_;
    JMOutlineTableView *tableView_;
    UIView *floatingHeader_;
    JMRefreshHeaderView *pullRefreshView_;
    UIImageView *_topShadowView;
    id <UIScrollViewDelegate> _scrollObserver;
    Class _customTableClass;
    unsigned int _selectedRow;
    unsigned int _topVisibleRow;
    double lastFloatRefresh_;
    struct CGPoint savedScrollPosition_;
}

- (void)setIsReloadingNodes:(BOOL)fp8;
- (BOOL)isReloadingNodes;
- (void)setTopVisibleRow:(unsigned int)fp8;
- (unsigned int)topVisibleRow;
- (void)setSelectedRow:(unsigned int)fp8;
- (unsigned int)selectedRow;
- (void)setCustomTableClass:(Class)fp8;
- (Class)customTableClass;
- (void)setScrollObserver:(id)fp8;
- (id)scrollObserver;
- (void)setTopShadowView:(id)fp8;
- (id)topShadowView;
- (void)setSavedScrollPosition:(struct CGPoint)fp8;
- (struct CGPoint)savedScrollPosition;
- (void)setPullRefreshView:(id)fp8;
- (id)pullRefreshView;
- (void)setLastFloatRefresh:(double)fp8;
- (double)lastFloatRefresh;
- (void)setFloatingHeader:(id)fp8;
- (id)floatingHeader;
- (void)setTableView:(id)fp8;
- (id)tableView;
- (void)setShowFloatingHeader:(BOOL)fp8;
- (BOOL)showFloatingHeader;
- (void)setNodes:(id)fp8;
- (id)nodes;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (BOOL)scrollViewShouldScrollToTop:(id)fp8;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)scrollViewDidEndScrollingAnimation:(id)fp8;
- (void)scrollViewWillBeginDecelerating:(id)fp8;
- (void)scrollViewWillBeginDragging:(id)fp8;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewWillEndDragging:(id)fp8 withVelocity:(struct CGPoint)fp12 targetContentOffset:(inout struct CGPoint *)fp20;
- (void)scrollViewDidScroll:(id)fp8;
- (void)updateFloatingHeader;
- (void)updateFloatingCell;
- (BOOL)tableView:(id)fp8 canEditRowAtIndexPath:(id)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)toggleNode:(id)fp8;
- (int)nodeCount;
- (void)scrollNodeRectToVisible:(id)fp8;
- (struct CGRect)rectForNode:(id)fp8;
- (void)scrollToNode:(id)fp8;
- (void)reloadVisibleRows;
- (void)reloadRowsForNodes:(id)fp8;
- (void)reloadRowForNode:(id)fp8;
- (void)reload;
- (id)cellForNode:(id)fp8;
- (void)deselectNodes;
- (void)selectNode:(id)fp8;
- (id)selectedNode;
- (BOOL)isNodeSelected:(id)fp8;
- (unsigned int)rowForNode:(id)fp8;
- (id)nodeForRow:(unsigned int)fp8;
- (void)removeAllNodes;
- (void)insertNode:(id)fp8 afterNode:(id)fp12;
- (void)insertNode:(id)fp8 atRowIndex:(unsigned int)fp12;
- (void)removeNode:(id)fp8;
- (void)addNodes:(id)fp8;
- (void)addNode:(id)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)loadView;
- (void)updateTopShadowWithLatestTableOffset;
- (void)viewWillLayoutSubviews;
- (void)createSubviews;
- (void)testFinished;
- (void)releaseViews;
- (id)init;
- (void)dealloc;
- (void)clearHeightCache;
- (void)clearCachedHeightForNode:(id)fp8;
- (void)setCachedHeight:(float)fp8 forNode:(id)fp12;
- (float)cachedHeightForNode:(id)fp8;
- (id)heightCacheKeyForNode:(id)fp8;
- (void)initialiseHeightCache;
- (void)setHeightCache:(id)fp8;
- (id)heightCache;
- (void)keyboardWillBeHidden:(id)fp8;
- (void)keyboardWasShown:(id)fp8;
- (void)disableKeyboardReaction;
- (void)enableKeyboardReaction;
- (void)setCurrentlyHandlingKeyboardEvent:(BOOL)fp8;
- (BOOL)currentlyHandlingKeyboardEvent;
- (void)clearRenderForNode:(id)fp8;
- (id)prerenderedCellImageForNode:(id)fp8;
- (void)prerenderNode:(id)fp8;
- (id)renderCacheKeyForNode:(id)fp8;
- (void)initialisePrerenderCache;
- (void)setRenderCache:(id)fp8;
- (id)renderCache;
- (void)handleRotationAdjustments;
- (void)customNavigationBarScrollHandler_didRotateFromInterfaceOrientation:(int)fp8;
- (void)customNavigationBarScrollHandler_willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (id)attachedCustomNavigationBar;
- (void)customNavigationBarScrollHandler_viewWillDisappear:(BOOL)fp8;
- (void)customNavigationBarScrollHandler_viewDidAppear:(BOOL)fp8;
- (void)customNavigationBarScrollHandler_viewWillAppear:(BOOL)fp8;
- (BOOL)customNavigationBarScrollHandler_scrollViewShouldScrollToTop:(id)fp8;
- (void)customNavigationBarScrollHandler_scrollViewWillEndDragging:(id)fp8 withVelocity:(struct CGPoint)fp12 targetContentOffset:(inout struct CGPoint *)fp20;
- (void)customNavigationBarScrollHandler_scrollViewDidScroll:(id)fp8;
- (void)properAdjustCustomNavigationBarForScrollView:(id)fp8;
- (BOOL)isScrollViewInPerpetualSlowDecelerationAnimation:(float)fp8;
- (void)customNavigationBarScrollHandler_scrollViewWillBeginDragging:(id)fp8;
- (void)customNavigationBarScrollHandler_scrollViewWillBeginDecelerating:(id)fp8;
- (void)customNavigationBarScrollHandler_scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)resetAggregateChangeIfNecessary;
- (void)customNavigationBarScrollHandler_scrollViewDidEndDecelerating:(id)fp8;
- (void)customNavigationBarScrollHandler_scrollViewDidEndScrollingAnimation:(id)fp8;
- (void)adjustInitialTableOffsets;
- (void)attachCustomNavigationBarView:(id)fp8;
- (void)detachCustomNavigationBarView;
- (BOOL)shouldUseCompactNavigationBar;
- (void)setTimeOfLastReportedScrollContentOffset:(float)fp8;
- (float)timeOfLastReportedScrollContentOffset;
- (void)setNavbarAggregateChangeWhileScrollViewIsPaused:(float)fp8;
- (float)navbarAggregateChangeWhileScrollViewIsPaused;
- (void)setLastReportedScrollContentOffset:(struct CGPoint)fp8;
- (struct CGPoint)lastReportedScrollContentOffset;
- (void)setIsAdjustingNavigationBar:(BOOL)fp8;
- (BOOL)isAdjustingNavigationBar;
- (void)setShouldSuppressNavigationBarAdjustmentResponse:(BOOL)fp8;
- (BOOL)shouldSuppressNavigationBarAdjustmentResponse;
- (void)setIsConfiguringNavigationBarForLandscape:(BOOL)fp8;
- (BOOL)isConfiguringNavigationBarForLandscape;
- (void)setPrefersFixedCompactCustomNavigationBar:(BOOL)fp8;
- (BOOL)prefersFixedCompactCustomNavigationBar;
- (void)setCustomNavigationBarView:(id)fp8;
- (id)customNavigationBarView;

@end

